### ISSUE TITLE
LibreSignal asks for Google Play Services

### ISSUE THREAD

**Issue by pizzamaker** [JavaJens/TextSecure#73]
I have tried both the experimental and the stable releases by @xmikos and both ask for Play Services after I type in my phone number. What gives?

**Comment by Diapolo** [comment]
Only the experimental release uses WebSockets for sending text etc., so you wont be able to use the calling functionality (RedPhone) AFAIK.

What do you mean by "type my phone number"?

**Comment by patcon** [comment]
They're referring to registration

**Comment by pizzamaker** [comment]
Correct, registration. I can't use the app at all, as it mandates (and even gives a link to download) play services.

**Comment by relyt29** [comment]
That's probably because xmikos hosts both upstream (requires gplay) and the websockets version on his f-droid repository. 

A) go through some of the closed issues on here, he has responses on how to deal with it

B) Actually build this repo from scratch and sideload the apk. Then if it keeps happening, get a debug log and maybe we can help more.

**Comment by pizzamaker** [comment]
Nevermind. The problem was that I had both eutopia and Guardian Project's repos enabled. I suppose I was actually downloading Signal instead of LibreSignal.
